name: CD

on:
  push:
    branches:
    - master

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Pack
      working-directory: ./SByteDev.MvvmCross.Extensions
      run: dotnet pack --configuration Release
    - name: Push to NuGet
      run: dotnet nuget push /**/*.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
