name: CD

on:
  push:
    branches:
    - master

jobs:
  build:
    
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Pack
      working-directory: ./SByteDev.MvvmCross.Extensions
      run: dotnet pack --configuration Release
    - name: Setup NuGet
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
    - name: Push to NuGet
      run: dotnet nuget push /**/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
