name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      working-directory: ./SByteDev.MvvmCross.Extensions

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup
      uses: actions/setup-dotnet@v1.4.0
    - name: Test
      working-directory: ${{ env.working-directory }}
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Test Coverage
      working-directory: ${{ env.working-directory }}
      run: curl -s https://codecov.io/bash | bash -s -- -t ${{secrets.CODECOV_TOKEN}} -Z
